{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Camera.CameraService exposing (openCamera)

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 6.33.1
  - the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs openCamera

-}

import Grpc.Internal
import Proto.Camera


{-| A template for a gRPC call to the method 'OpenCamera' sending a `OpenCameraRequest` to get back a `OpenCameraResponse`.
-}
openCamera : Grpc.Internal.Rpc Proto.Camera.OpenCameraRequest Proto.Camera.OpenCameraResponse
openCamera =
    Grpc.Internal.Rpc
        { service = "CameraService"
        , package = "camera"
        , rpcName = "OpenCamera"
        , encoder = Proto.Camera.encodeOpenCameraRequest
        , decoder = Proto.Camera.decodeOpenCameraResponse
        }
