{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera.Internals_ exposing (Proto__Camera__OpenCameraRequest, Proto__Camera__OpenCameraResponse, decodeProto__Camera__OpenCameraRequest, decodeProto__Camera__OpenCameraResponse, defaultProto__Camera__OpenCameraRequest, defaultProto__Camera__OpenCameraResponse, encodeProto__Camera__OpenCameraRequest, encodeProto__Camera__OpenCameraResponse, fieldNumbersProto__Camera__OpenCameraRequest, fieldNumbersProto__Camera__OpenCameraResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Proto__Camera__OpenCameraRequest, Proto__Camera__OpenCameraResponse, decodeProto__Camera__OpenCameraRequest

@docs decodeProto__Camera__OpenCameraResponse, defaultProto__Camera__OpenCameraRequest, defaultProto__Camera__OpenCameraResponse

@docs encodeProto__Camera__OpenCameraRequest, encodeProto__Camera__OpenCameraResponse

@docs fieldNumbersProto__Camera__OpenCameraRequest, fieldNumbersProto__Camera__OpenCameraResponse

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Proto__Camera__OpenCameraResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__OpenCameraResponse : { message : Int }
fieldNumbersProto__Camera__OpenCameraResponse =
    { message = 1 }


{-| Default for Proto__Camera__OpenCameraResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__OpenCameraResponse : Proto__Camera__OpenCameraResponse
defaultProto__Camera__OpenCameraResponse =
    { message = "" }


{-| Declares how to decode a `Proto__Camera__OpenCameraResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__OpenCameraResponse : Protobuf.Decode.Decoder Proto__Camera__OpenCameraResponse
decodeProto__Camera__OpenCameraResponse =
    Protobuf.Decode.message
        defaultProto__Camera__OpenCameraResponse
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | message = a }) ]


{-| Declares how to encode a `Proto__Camera__OpenCameraResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__OpenCameraResponse : Proto__Camera__OpenCameraResponse -> Protobuf.Encode.Encoder
encodeProto__Camera__OpenCameraResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.message ) ]


{-| `Proto__Camera__OpenCameraResponse` message

-}
type alias Proto__Camera__OpenCameraResponse =
    { message : String }


{-| The field numbers for the fields of `Proto__Camera__OpenCameraRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__OpenCameraRequest : { name : Int }
fieldNumbersProto__Camera__OpenCameraRequest =
    { name = 1 }


{-| Default for Proto__Camera__OpenCameraRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__OpenCameraRequest : Proto__Camera__OpenCameraRequest
defaultProto__Camera__OpenCameraRequest =
    { name = "" }


{-| Declares how to decode a `Proto__Camera__OpenCameraRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__OpenCameraRequest : Protobuf.Decode.Decoder Proto__Camera__OpenCameraRequest
decodeProto__Camera__OpenCameraRequest =
    Protobuf.Decode.message
        defaultProto__Camera__OpenCameraRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a }) ]


{-| Declares how to encode a `Proto__Camera__OpenCameraRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__OpenCameraRequest : Proto__Camera__OpenCameraRequest -> Protobuf.Encode.Encoder
encodeProto__Camera__OpenCameraRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.name ) ]


{-| `Proto__Camera__OpenCameraRequest` message

-}
type alias Proto__Camera__OpenCameraRequest =
    { name : String }
