{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera.Internals_ exposing (Proto__Camera__GetImageRequest, Proto__Camera__GetImageResponse, Proto__Camera__OpenCameraRequest, Proto__Camera__OpenCameraResponse, decodeProto__Camera__GetImageRequest, decodeProto__Camera__GetImageResponse, decodeProto__Camera__OpenCameraRequest, decodeProto__Camera__OpenCameraResponse, defaultProto__Camera__GetImageRequest, defaultProto__Camera__GetImageResponse, defaultProto__Camera__OpenCameraRequest, defaultProto__Camera__OpenCameraResponse, encodeProto__Camera__GetImageRequest, encodeProto__Camera__GetImageResponse, encodeProto__Camera__OpenCameraRequest, encodeProto__Camera__OpenCameraResponse, fieldNumbersProto__Camera__GetImageRequest, fieldNumbersProto__Camera__GetImageResponse, fieldNumbersProto__Camera__OpenCameraRequest, fieldNumbersProto__Camera__OpenCameraResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Proto__Camera__GetImageRequest, Proto__Camera__GetImageResponse, Proto__Camera__OpenCameraRequest

@docs Proto__Camera__OpenCameraResponse, decodeProto__Camera__GetImageRequest, decodeProto__Camera__GetImageResponse

@docs decodeProto__Camera__OpenCameraRequest, decodeProto__Camera__OpenCameraResponse, defaultProto__Camera__GetImageRequest

@docs defaultProto__Camera__GetImageResponse, defaultProto__Camera__OpenCameraRequest, defaultProto__Camera__OpenCameraResponse

@docs encodeProto__Camera__GetImageRequest, encodeProto__Camera__GetImageResponse, encodeProto__Camera__OpenCameraRequest

@docs encodeProto__Camera__OpenCameraResponse, fieldNumbersProto__Camera__GetImageRequest

@docs fieldNumbersProto__Camera__GetImageResponse, fieldNumbersProto__Camera__OpenCameraRequest

@docs fieldNumbersProto__Camera__OpenCameraResponse

-}

import Bytes
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Proto__Camera__GetImageResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__GetImageResponse : { image : Int, position : Int }
fieldNumbersProto__Camera__GetImageResponse =
    { image = 1, position = 2 }


{-| Default for Proto__Camera__GetImageResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__GetImageResponse : Proto__Camera__GetImageResponse
defaultProto__Camera__GetImageResponse =
    { image = Protobuf.Encode.encode <| Protobuf.Encode.string "", position = 0 }


{-| Declares how to decode a `Proto__Camera__GetImageResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__GetImageResponse : Protobuf.Decode.Decoder Proto__Camera__GetImageResponse
decodeProto__Camera__GetImageResponse =
    Protobuf.Decode.message
        defaultProto__Camera__GetImageResponse
        [ Protobuf.Decode.optional 1 Protobuf.Decode.bytes (\a r -> { r | image = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.int32 (\a r -> { r | position = a })
        ]


{-| Declares how to encode a `Proto__Camera__GetImageResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__GetImageResponse : Proto__Camera__GetImageResponse -> Protobuf.Encode.Encoder
encodeProto__Camera__GetImageResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.bytes value.image ), ( 2, Protobuf.Encode.int32 value.position ) ]


{-| `Proto__Camera__GetImageResponse` message

-}
type alias Proto__Camera__GetImageResponse =
    { image : Bytes.Bytes, position : Int }


{-| The field numbers for the fields of `Proto__Camera__GetImageRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__GetImageRequest : { id : Int }
fieldNumbersProto__Camera__GetImageRequest =
    { id = 1 }


{-| Default for Proto__Camera__GetImageRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__GetImageRequest : Proto__Camera__GetImageRequest
defaultProto__Camera__GetImageRequest =
    { id = 0 }


{-| Declares how to decode a `Proto__Camera__GetImageRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__GetImageRequest : Protobuf.Decode.Decoder Proto__Camera__GetImageRequest
decodeProto__Camera__GetImageRequest =
    Protobuf.Decode.message
        defaultProto__Camera__GetImageRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.int32 (\a r -> { r | id = a }) ]


{-| Declares how to encode a `Proto__Camera__GetImageRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__GetImageRequest : Proto__Camera__GetImageRequest -> Protobuf.Encode.Encoder
encodeProto__Camera__GetImageRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.int32 value.id ) ]


{-| `Proto__Camera__GetImageRequest` message

-}
type alias Proto__Camera__GetImageRequest =
    { id : Int }


{-| The field numbers for the fields of `Proto__Camera__OpenCameraResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__OpenCameraResponse : { message : Int }
fieldNumbersProto__Camera__OpenCameraResponse =
    { message = 1 }


{-| Default for Proto__Camera__OpenCameraResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__OpenCameraResponse : Proto__Camera__OpenCameraResponse
defaultProto__Camera__OpenCameraResponse =
    { message = "" }


{-| Declares how to decode a `Proto__Camera__OpenCameraResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__OpenCameraResponse : Protobuf.Decode.Decoder Proto__Camera__OpenCameraResponse
decodeProto__Camera__OpenCameraResponse =
    Protobuf.Decode.message
        defaultProto__Camera__OpenCameraResponse
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | message = a }) ]


{-| Declares how to encode a `Proto__Camera__OpenCameraResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__OpenCameraResponse : Proto__Camera__OpenCameraResponse -> Protobuf.Encode.Encoder
encodeProto__Camera__OpenCameraResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.message ) ]


{-| `Proto__Camera__OpenCameraResponse` message

-}
type alias Proto__Camera__OpenCameraResponse =
    { message : String }


{-| The field numbers for the fields of `Proto__Camera__OpenCameraRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__OpenCameraRequest : { id : Int }
fieldNumbersProto__Camera__OpenCameraRequest =
    { id = 1 }


{-| Default for Proto__Camera__OpenCameraRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__OpenCameraRequest : Proto__Camera__OpenCameraRequest
defaultProto__Camera__OpenCameraRequest =
    { id = 0 }


{-| Declares how to decode a `Proto__Camera__OpenCameraRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__OpenCameraRequest : Protobuf.Decode.Decoder Proto__Camera__OpenCameraRequest
decodeProto__Camera__OpenCameraRequest =
    Protobuf.Decode.message
        defaultProto__Camera__OpenCameraRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.int32 (\a r -> { r | id = a }) ]


{-| Declares how to encode a `Proto__Camera__OpenCameraRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__OpenCameraRequest : Proto__Camera__OpenCameraRequest -> Protobuf.Encode.Encoder
encodeProto__Camera__OpenCameraRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.int32 value.id ) ]


{-| `Proto__Camera__OpenCameraRequest` message

-}
type alias Proto__Camera__OpenCameraRequest =
    { id : Int }
