{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera exposing (GetCameraListRequest, GetCameraListResponse, decodeGetCameraListRequest, decodeGetCameraListResponse, defaultGetCameraListRequest, defaultGetCameraListResponse, encodeGetCameraListRequest, encodeGetCameraListResponse, fieldNumbersGetCameraListRequest, fieldNumbersGetCameraListResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs GetCameraListRequest, GetCameraListResponse, decodeGetCameraListRequest, decodeGetCameraListResponse

@docs defaultGetCameraListRequest, defaultGetCameraListResponse, encodeGetCameraListRequest, encodeGetCameraListResponse

@docs fieldNumbersGetCameraListRequest, fieldNumbersGetCameraListResponse

-}

import Proto.Camera.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `GetCameraListResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetCameraListResponse : { cameraList : Int }
fieldNumbersGetCameraListResponse =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetCameraListResponse


{-| Default for GetCameraListResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultGetCameraListResponse : GetCameraListResponse
defaultGetCameraListResponse =
    Proto.Camera.Internals_.defaultProto__Camera__GetCameraListResponse


{-| Declares how to decode a `GetCameraListResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetCameraListResponse : Protobuf.Decode.Decoder GetCameraListResponse
decodeGetCameraListResponse =
    Proto.Camera.Internals_.decodeProto__Camera__GetCameraListResponse


{-| Declares how to encode a `GetCameraListResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetCameraListResponse : GetCameraListResponse -> Protobuf.Encode.Encoder
encodeGetCameraListResponse =
    Proto.Camera.Internals_.encodeProto__Camera__GetCameraListResponse


{-| `GetCameraListResponse` message

-}
type alias GetCameraListResponse =
    Proto.Camera.Internals_.Proto__Camera__GetCameraListResponse


{-| The field numbers for the fields of `GetCameraListRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetCameraListRequest : {}
fieldNumbersGetCameraListRequest =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetCameraListRequest


{-| Default for GetCameraListRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultGetCameraListRequest : GetCameraListRequest
defaultGetCameraListRequest =
    Proto.Camera.Internals_.defaultProto__Camera__GetCameraListRequest


{-| Declares how to decode a `GetCameraListRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetCameraListRequest : Protobuf.Decode.Decoder GetCameraListRequest
decodeGetCameraListRequest =
    Proto.Camera.Internals_.decodeProto__Camera__GetCameraListRequest


{-| Declares how to encode a `GetCameraListRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetCameraListRequest : GetCameraListRequest -> Protobuf.Encode.Encoder
encodeGetCameraListRequest =
    Proto.Camera.Internals_.encodeProto__Camera__GetCameraListRequest


{-| `GetCameraListRequest` message

-}
type alias GetCameraListRequest =
    Proto.Camera.Internals_.Proto__Camera__GetCameraListRequest
