{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera exposing (GetCameraListRequest, GetCameraListResponse, GetLatestCameraFrameRequest, GetLatestCameraFrameResponse, decodeGetCameraListRequest, decodeGetCameraListResponse, decodeGetLatestCameraFrameRequest, decodeGetLatestCameraFrameResponse, defaultGetCameraListRequest, defaultGetCameraListResponse, defaultGetLatestCameraFrameRequest, defaultGetLatestCameraFrameResponse, encodeGetCameraListRequest, encodeGetCameraListResponse, encodeGetLatestCameraFrameRequest, encodeGetLatestCameraFrameResponse, fieldNumbersGetCameraListRequest, fieldNumbersGetCameraListResponse, fieldNumbersGetLatestCameraFrameRequest, fieldNumbersGetLatestCameraFrameResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs GetCameraListRequest, GetCameraListResponse, GetLatestCameraFrameRequest, GetLatestCameraFrameResponse

@docs decodeGetCameraListRequest, decodeGetCameraListResponse, decodeGetLatestCameraFrameRequest, decodeGetLatestCameraFrameResponse

@docs defaultGetCameraListRequest, defaultGetCameraListResponse, defaultGetLatestCameraFrameRequest

@docs defaultGetLatestCameraFrameResponse, encodeGetCameraListRequest, encodeGetCameraListResponse

@docs encodeGetLatestCameraFrameRequest, encodeGetLatestCameraFrameResponse, fieldNumbersGetCameraListRequest

@docs fieldNumbersGetCameraListResponse, fieldNumbersGetLatestCameraFrameRequest, fieldNumbersGetLatestCameraFrameResponse

-}

import Proto.Camera.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `GetLatestCameraFrameResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetLatestCameraFrameResponse : { frame : Int }
fieldNumbersGetLatestCameraFrameResponse =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetLatestCameraFrameResponse


{-| Default for GetLatestCameraFrameResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultGetLatestCameraFrameResponse : GetLatestCameraFrameResponse
defaultGetLatestCameraFrameResponse =
    Proto.Camera.Internals_.defaultProto__Camera__GetLatestCameraFrameResponse


{-| Declares how to decode a `GetLatestCameraFrameResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetLatestCameraFrameResponse : Protobuf.Decode.Decoder GetLatestCameraFrameResponse
decodeGetLatestCameraFrameResponse =
    Proto.Camera.Internals_.decodeProto__Camera__GetLatestCameraFrameResponse


{-| Declares how to encode a `GetLatestCameraFrameResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetLatestCameraFrameResponse : GetLatestCameraFrameResponse -> Protobuf.Encode.Encoder
encodeGetLatestCameraFrameResponse =
    Proto.Camera.Internals_.encodeProto__Camera__GetLatestCameraFrameResponse


{-| `GetLatestCameraFrameResponse` message

-}
type alias GetLatestCameraFrameResponse =
    Proto.Camera.Internals_.Proto__Camera__GetLatestCameraFrameResponse


{-| The field numbers for the fields of `GetLatestCameraFrameRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetLatestCameraFrameRequest : { cameraName : Int }
fieldNumbersGetLatestCameraFrameRequest =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetLatestCameraFrameRequest


{-| Default for GetLatestCameraFrameRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultGetLatestCameraFrameRequest : GetLatestCameraFrameRequest
defaultGetLatestCameraFrameRequest =
    Proto.Camera.Internals_.defaultProto__Camera__GetLatestCameraFrameRequest


{-| Declares how to decode a `GetLatestCameraFrameRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetLatestCameraFrameRequest : Protobuf.Decode.Decoder GetLatestCameraFrameRequest
decodeGetLatestCameraFrameRequest =
    Proto.Camera.Internals_.decodeProto__Camera__GetLatestCameraFrameRequest


{-| Declares how to encode a `GetLatestCameraFrameRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetLatestCameraFrameRequest : GetLatestCameraFrameRequest -> Protobuf.Encode.Encoder
encodeGetLatestCameraFrameRequest =
    Proto.Camera.Internals_.encodeProto__Camera__GetLatestCameraFrameRequest


{-| `GetLatestCameraFrameRequest` message

-}
type alias GetLatestCameraFrameRequest =
    Proto.Camera.Internals_.Proto__Camera__GetLatestCameraFrameRequest


{-| The field numbers for the fields of `GetCameraListResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetCameraListResponse : { cameraList : Int }
fieldNumbersGetCameraListResponse =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetCameraListResponse


{-| Default for GetCameraListResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultGetCameraListResponse : GetCameraListResponse
defaultGetCameraListResponse =
    Proto.Camera.Internals_.defaultProto__Camera__GetCameraListResponse


{-| Declares how to decode a `GetCameraListResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetCameraListResponse : Protobuf.Decode.Decoder GetCameraListResponse
decodeGetCameraListResponse =
    Proto.Camera.Internals_.decodeProto__Camera__GetCameraListResponse


{-| Declares how to encode a `GetCameraListResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetCameraListResponse : GetCameraListResponse -> Protobuf.Encode.Encoder
encodeGetCameraListResponse =
    Proto.Camera.Internals_.encodeProto__Camera__GetCameraListResponse


{-| `GetCameraListResponse` message

-}
type alias GetCameraListResponse =
    Proto.Camera.Internals_.Proto__Camera__GetCameraListResponse


{-| The field numbers for the fields of `GetCameraListRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetCameraListRequest : {}
fieldNumbersGetCameraListRequest =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetCameraListRequest


{-| Default for GetCameraListRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultGetCameraListRequest : GetCameraListRequest
defaultGetCameraListRequest =
    Proto.Camera.Internals_.defaultProto__Camera__GetCameraListRequest


{-| Declares how to decode a `GetCameraListRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetCameraListRequest : Protobuf.Decode.Decoder GetCameraListRequest
decodeGetCameraListRequest =
    Proto.Camera.Internals_.decodeProto__Camera__GetCameraListRequest


{-| Declares how to encode a `GetCameraListRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetCameraListRequest : GetCameraListRequest -> Protobuf.Encode.Encoder
encodeGetCameraListRequest =
    Proto.Camera.Internals_.encodeProto__Camera__GetCameraListRequest


{-| `GetCameraListRequest` message

-}
type alias GetCameraListRequest =
    Proto.Camera.Internals_.Proto__Camera__GetCameraListRequest
