{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Camera exposing
    ( OpenCameraRequest, OpenCameraResponse, decodeOpenCameraRequest, decodeOpenCameraResponse, defaultOpenCameraRequest
    , defaultOpenCameraResponse, encodeOpenCameraRequest, encodeOpenCameraResponse, fieldNumbersOpenCameraRequest
    , fieldNumbersOpenCameraResponse
    )

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 6.33.1
  - the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs OpenCameraRequest, OpenCameraResponse, decodeOpenCameraRequest, decodeOpenCameraResponse, defaultOpenCameraRequest

@docs defaultOpenCameraResponse, encodeOpenCameraRequest, encodeOpenCameraResponse, fieldNumbersOpenCameraRequest

@docs fieldNumbersOpenCameraResponse

-}

import Proto.Camera.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `OpenCameraResponse`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersOpenCameraResponse : { message : Int }
fieldNumbersOpenCameraResponse =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__OpenCameraResponse


{-| Default for OpenCameraResponse. Should only be used for 'required' decoders as an initial value.
-}
defaultOpenCameraResponse : OpenCameraResponse
defaultOpenCameraResponse =
    Proto.Camera.Internals_.defaultProto__Camera__OpenCameraResponse


{-| Declares how to decode a `OpenCameraResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeOpenCameraResponse : Protobuf.Decode.Decoder OpenCameraResponse
decodeOpenCameraResponse =
    Proto.Camera.Internals_.decodeProto__Camera__OpenCameraResponse


{-| Declares how to encode a `OpenCameraResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeOpenCameraResponse : OpenCameraResponse -> Protobuf.Encode.Encoder
encodeOpenCameraResponse =
    Proto.Camera.Internals_.encodeProto__Camera__OpenCameraResponse


{-| `OpenCameraResponse` message
-}
type alias OpenCameraResponse =
    Proto.Camera.Internals_.Proto__Camera__OpenCameraResponse


{-| The field numbers for the fields of `OpenCameraRequest`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersOpenCameraRequest : { name : Int }
fieldNumbersOpenCameraRequest =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__OpenCameraRequest


{-| Default for OpenCameraRequest. Should only be used for 'required' decoders as an initial value.
-}
defaultOpenCameraRequest : OpenCameraRequest
defaultOpenCameraRequest =
    Proto.Camera.Internals_.defaultProto__Camera__OpenCameraRequest


{-| Declares how to decode a `OpenCameraRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeOpenCameraRequest : Protobuf.Decode.Decoder OpenCameraRequest
decodeOpenCameraRequest =
    Proto.Camera.Internals_.decodeProto__Camera__OpenCameraRequest


{-| Declares how to encode a `OpenCameraRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeOpenCameraRequest : OpenCameraRequest -> Protobuf.Encode.Encoder
encodeOpenCameraRequest =
    Proto.Camera.Internals_.encodeProto__Camera__OpenCameraRequest


{-| `OpenCameraRequest` message
-}
type alias OpenCameraRequest =
    Proto.Camera.Internals_.Proto__Camera__OpenCameraRequest
