{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera exposing (GetImageRequest, GetImageResponse, OpenCameraRequest, OpenCameraResponse, decodeGetImageRequest, decodeGetImageResponse, decodeOpenCameraRequest, decodeOpenCameraResponse, defaultGetImageRequest, defaultGetImageResponse, defaultOpenCameraRequest, defaultOpenCameraResponse, encodeGetImageRequest, encodeGetImageResponse, encodeOpenCameraRequest, encodeOpenCameraResponse, fieldNumbersGetImageRequest, fieldNumbersGetImageResponse, fieldNumbersOpenCameraRequest, fieldNumbersOpenCameraResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs GetImageRequest, GetImageResponse, OpenCameraRequest, OpenCameraResponse, decodeGetImageRequest, decodeGetImageResponse

@docs decodeOpenCameraRequest, decodeOpenCameraResponse, defaultGetImageRequest, defaultGetImageResponse, defaultOpenCameraRequest

@docs defaultOpenCameraResponse, encodeGetImageRequest, encodeGetImageResponse, encodeOpenCameraRequest, encodeOpenCameraResponse

@docs fieldNumbersGetImageRequest, fieldNumbersGetImageResponse, fieldNumbersOpenCameraRequest, fieldNumbersOpenCameraResponse

-}

import Proto.Camera.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `GetImageResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetImageResponse : { image : Int, position : Int }
fieldNumbersGetImageResponse =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetImageResponse


{-| Default for GetImageResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultGetImageResponse : GetImageResponse
defaultGetImageResponse =
    Proto.Camera.Internals_.defaultProto__Camera__GetImageResponse


{-| Declares how to decode a `GetImageResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetImageResponse : Protobuf.Decode.Decoder GetImageResponse
decodeGetImageResponse =
    Proto.Camera.Internals_.decodeProto__Camera__GetImageResponse


{-| Declares how to encode a `GetImageResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetImageResponse : GetImageResponse -> Protobuf.Encode.Encoder
encodeGetImageResponse =
    Proto.Camera.Internals_.encodeProto__Camera__GetImageResponse


{-| `GetImageResponse` message

-}
type alias GetImageResponse =
    Proto.Camera.Internals_.Proto__Camera__GetImageResponse


{-| The field numbers for the fields of `GetImageRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetImageRequest : { id : Int }
fieldNumbersGetImageRequest =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__GetImageRequest


{-| Default for GetImageRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultGetImageRequest : GetImageRequest
defaultGetImageRequest =
    Proto.Camera.Internals_.defaultProto__Camera__GetImageRequest


{-| Declares how to decode a `GetImageRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetImageRequest : Protobuf.Decode.Decoder GetImageRequest
decodeGetImageRequest =
    Proto.Camera.Internals_.decodeProto__Camera__GetImageRequest


{-| Declares how to encode a `GetImageRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetImageRequest : GetImageRequest -> Protobuf.Encode.Encoder
encodeGetImageRequest =
    Proto.Camera.Internals_.encodeProto__Camera__GetImageRequest


{-| `GetImageRequest` message

-}
type alias GetImageRequest =
    Proto.Camera.Internals_.Proto__Camera__GetImageRequest


{-| The field numbers for the fields of `OpenCameraResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersOpenCameraResponse : { message : Int }
fieldNumbersOpenCameraResponse =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__OpenCameraResponse


{-| Default for OpenCameraResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultOpenCameraResponse : OpenCameraResponse
defaultOpenCameraResponse =
    Proto.Camera.Internals_.defaultProto__Camera__OpenCameraResponse


{-| Declares how to decode a `OpenCameraResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeOpenCameraResponse : Protobuf.Decode.Decoder OpenCameraResponse
decodeOpenCameraResponse =
    Proto.Camera.Internals_.decodeProto__Camera__OpenCameraResponse


{-| Declares how to encode a `OpenCameraResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeOpenCameraResponse : OpenCameraResponse -> Protobuf.Encode.Encoder
encodeOpenCameraResponse =
    Proto.Camera.Internals_.encodeProto__Camera__OpenCameraResponse


{-| `OpenCameraResponse` message

-}
type alias OpenCameraResponse =
    Proto.Camera.Internals_.Proto__Camera__OpenCameraResponse


{-| The field numbers for the fields of `OpenCameraRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersOpenCameraRequest : { id : Int }
fieldNumbersOpenCameraRequest =
    Proto.Camera.Internals_.fieldNumbersProto__Camera__OpenCameraRequest


{-| Default for OpenCameraRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultOpenCameraRequest : OpenCameraRequest
defaultOpenCameraRequest =
    Proto.Camera.Internals_.defaultProto__Camera__OpenCameraRequest


{-| Declares how to decode a `OpenCameraRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeOpenCameraRequest : Protobuf.Decode.Decoder OpenCameraRequest
decodeOpenCameraRequest =
    Proto.Camera.Internals_.decodeProto__Camera__OpenCameraRequest


{-| Declares how to encode a `OpenCameraRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeOpenCameraRequest : OpenCameraRequest -> Protobuf.Encode.Encoder
encodeOpenCameraRequest =
    Proto.Camera.Internals_.encodeProto__Camera__OpenCameraRequest


{-| `OpenCameraRequest` message

-}
type alias OpenCameraRequest =
    Proto.Camera.Internals_.Proto__Camera__OpenCameraRequest
