{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera.Internals_ exposing (Proto__Camera__GetCameraListRequest, Proto__Camera__GetCameraListResponse, decodeProto__Camera__GetCameraListRequest, decodeProto__Camera__GetCameraListResponse, defaultProto__Camera__GetCameraListRequest, defaultProto__Camera__GetCameraListResponse, encodeProto__Camera__GetCameraListRequest, encodeProto__Camera__GetCameraListResponse, fieldNumbersProto__Camera__GetCameraListRequest, fieldNumbersProto__Camera__GetCameraListResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Proto__Camera__GetCameraListRequest, Proto__Camera__GetCameraListResponse, decodeProto__Camera__GetCameraListRequest

@docs decodeProto__Camera__GetCameraListResponse, defaultProto__Camera__GetCameraListRequest

@docs defaultProto__Camera__GetCameraListResponse, encodeProto__Camera__GetCameraListRequest

@docs encodeProto__Camera__GetCameraListResponse, fieldNumbersProto__Camera__GetCameraListRequest

@docs fieldNumbersProto__Camera__GetCameraListResponse

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Proto__Camera__GetCameraListResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__GetCameraListResponse : { cameraList : Int }
fieldNumbersProto__Camera__GetCameraListResponse =
    { cameraList = 1 }


{-| Default for Proto__Camera__GetCameraListResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__GetCameraListResponse : Proto__Camera__GetCameraListResponse
defaultProto__Camera__GetCameraListResponse =
    { cameraList = [] }


{-| Declares how to decode a `Proto__Camera__GetCameraListResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__GetCameraListResponse : Protobuf.Decode.Decoder Proto__Camera__GetCameraListResponse
decodeProto__Camera__GetCameraListResponse =
    Protobuf.Decode.message
        defaultProto__Camera__GetCameraListResponse
        [ Protobuf.Decode.repeated 1 Protobuf.Decode.string .cameraList (\a r -> { r | cameraList = a }) ]


{-| Declares how to encode a `Proto__Camera__GetCameraListResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__GetCameraListResponse : Proto__Camera__GetCameraListResponse -> Protobuf.Encode.Encoder
encodeProto__Camera__GetCameraListResponse value =
    Protobuf.Encode.message [ ( 1, (Protobuf.Encode.list Protobuf.Encode.string) value.cameraList ) ]


{-| `Proto__Camera__GetCameraListResponse` message

-}
type alias Proto__Camera__GetCameraListResponse =
    { cameraList : List String }


{-| The field numbers for the fields of `Proto__Camera__GetCameraListRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Camera__GetCameraListRequest : {}
fieldNumbersProto__Camera__GetCameraListRequest =
    {}


{-| Default for Proto__Camera__GetCameraListRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Camera__GetCameraListRequest : Proto__Camera__GetCameraListRequest
defaultProto__Camera__GetCameraListRequest =
    {}


{-| Declares how to decode a `Proto__Camera__GetCameraListRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Camera__GetCameraListRequest : Protobuf.Decode.Decoder Proto__Camera__GetCameraListRequest
decodeProto__Camera__GetCameraListRequest =
    Protobuf.Decode.message defaultProto__Camera__GetCameraListRequest []


{-| Declares how to encode a `Proto__Camera__GetCameraListRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Camera__GetCameraListRequest : Proto__Camera__GetCameraListRequest -> Protobuf.Encode.Encoder
encodeProto__Camera__GetCameraListRequest _ =
    Protobuf.Encode.message []


{-| `Proto__Camera__GetCameraListRequest` message

-}
type alias Proto__Camera__GetCameraListRequest =
    {}
