// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file camera.proto (package camera, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file camera.proto.
 */
export const file_camera: GenFile = /*@__PURE__*/
  fileDesc("CgxjYW1lcmEucHJvdG8SBmNhbWVyYSIWChRHZXRDYW1lcmFMaXN0UmVxdWVzdCIsChVHZXRDYW1lcmFMaXN0UmVzcG9uc2USEwoLY2FtZXJhX2xpc3QYASADKAkiMgobR2V0TGF0ZXN0Q2FtZXJhRnJhbWVSZXF1ZXN0EhMKC2NhbWVyYV9uYW1lGAEgASgJIi0KHEdldExhdGVzdENhbWVyYUZyYW1lUmVzcG9uc2USDQoFZnJhbWUYASABKAwiOQoiR2V0TGF0ZXN0VmlydHVhbENhbWVyYUZyYW1lUmVxdWVzdBITCgtjYW1lcmFfbmFtZRgBIAEoCSI0CiNHZXRMYXRlc3RWaXJ0dWFsQ2FtZXJhRnJhbWVSZXNwb25zZRINCgVmcmFtZRgBIAEoDCJOCh1TZXRWaXJ0dWFsQ2FtZXJhQ29uZmlnUmVxdWVzdBITCgtjYW1lcmFfbmFtZRgBIAEoCRIYChByZXNvbHV0aW9uX3JhdGlvGAIgASgCIiAKHlNldFZpcnR1YWxDYW1lcmFDb25maWdSZXNwb25zZSIyChtQdWJsaXNoVmlydHVhbENhbWVyYVJlcXVlc3QSEwoLY2FtZXJhX25hbWUYASABKAkiHgocUHVibGlzaFZpcnR1YWxDYW1lcmFSZXNwb25zZSI0Ch1VbnB1Ymxpc2hWaXJ0dWFsQ2FtZXJhUmVxdWVzdBITCgtjYW1lcmFfbmFtZRgBIAEoCSIgCh5VbnB1Ymxpc2hWaXJ0dWFsQ2FtZXJhUmVzcG9uc2Uy7QQKDUNhbWVyYVNlcnZpY2USTAoNR2V0Q2FtZXJhTGlzdBIcLmNhbWVyYS5HZXRDYW1lcmFMaXN0UmVxdWVzdBodLmNhbWVyYS5HZXRDYW1lcmFMaXN0UmVzcG9uc2USYQoUR2V0TGF0ZXN0Q2FtZXJhRnJhbWUSIy5jYW1lcmEuR2V0TGF0ZXN0Q2FtZXJhRnJhbWVSZXF1ZXN0GiQuY2FtZXJhLkdldExhdGVzdENhbWVyYUZyYW1lUmVzcG9uc2USdgobR2V0TGF0ZXN0VmlydHVhbENhbWVyYUZyYW1lEiouY2FtZXJhLkdldExhdGVzdFZpcnR1YWxDYW1lcmFGcmFtZVJlcXVlc3QaKy5jYW1lcmEuR2V0TGF0ZXN0VmlydHVhbENhbWVyYUZyYW1lUmVzcG9uc2USZwoWU2V0VmlydHVhbENhbWVyYUNvbmZpZxIlLmNhbWVyYS5TZXRWaXJ0dWFsQ2FtZXJhQ29uZmlnUmVxdWVzdBomLmNhbWVyYS5TZXRWaXJ0dWFsQ2FtZXJhQ29uZmlnUmVzcG9uc2USYQoUUHVibGlzaFZpcnR1YWxDYW1lcmESIy5jYW1lcmEuUHVibGlzaFZpcnR1YWxDYW1lcmFSZXF1ZXN0GiQuY2FtZXJhLlB1Ymxpc2hWaXJ0dWFsQ2FtZXJhUmVzcG9uc2USZwoWVW5wdWJsaXNoVmlydHVhbENhbWVyYRIlLmNhbWVyYS5VbnB1Ymxpc2hWaXJ0dWFsQ2FtZXJhUmVxdWVzdBomLmNhbWVyYS5VbnB1Ymxpc2hWaXJ0dWFsQ2FtZXJhUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message camera.GetCameraListRequest
 */
export type GetCameraListRequest = Message<"camera.GetCameraListRequest"> & {
};

/**
 * Describes the message camera.GetCameraListRequest.
 * Use `create(GetCameraListRequestSchema)` to create a new message.
 */
export const GetCameraListRequestSchema: GenMessage<GetCameraListRequest> = /*@__PURE__*/
  messageDesc(file_camera, 0);

/**
 * @generated from message camera.GetCameraListResponse
 */
export type GetCameraListResponse = Message<"camera.GetCameraListResponse"> & {
  /**
   * @generated from field: repeated string camera_list = 1;
   */
  cameraList: string[];
};

/**
 * Describes the message camera.GetCameraListResponse.
 * Use `create(GetCameraListResponseSchema)` to create a new message.
 */
export const GetCameraListResponseSchema: GenMessage<GetCameraListResponse> = /*@__PURE__*/
  messageDesc(file_camera, 1);

/**
 * @generated from message camera.GetLatestCameraFrameRequest
 */
export type GetLatestCameraFrameRequest = Message<"camera.GetLatestCameraFrameRequest"> & {
  /**
   * @generated from field: string camera_name = 1;
   */
  cameraName: string;
};

/**
 * Describes the message camera.GetLatestCameraFrameRequest.
 * Use `create(GetLatestCameraFrameRequestSchema)` to create a new message.
 */
export const GetLatestCameraFrameRequestSchema: GenMessage<GetLatestCameraFrameRequest> = /*@__PURE__*/
  messageDesc(file_camera, 2);

/**
 * @generated from message camera.GetLatestCameraFrameResponse
 */
export type GetLatestCameraFrameResponse = Message<"camera.GetLatestCameraFrameResponse"> & {
  /**
   * @generated from field: bytes frame = 1;
   */
  frame: Uint8Array;
};

/**
 * Describes the message camera.GetLatestCameraFrameResponse.
 * Use `create(GetLatestCameraFrameResponseSchema)` to create a new message.
 */
export const GetLatestCameraFrameResponseSchema: GenMessage<GetLatestCameraFrameResponse> = /*@__PURE__*/
  messageDesc(file_camera, 3);

/**
 * @generated from message camera.GetLatestVirtualCameraFrameRequest
 */
export type GetLatestVirtualCameraFrameRequest = Message<"camera.GetLatestVirtualCameraFrameRequest"> & {
  /**
   * @generated from field: string camera_name = 1;
   */
  cameraName: string;
};

/**
 * Describes the message camera.GetLatestVirtualCameraFrameRequest.
 * Use `create(GetLatestVirtualCameraFrameRequestSchema)` to create a new message.
 */
export const GetLatestVirtualCameraFrameRequestSchema: GenMessage<GetLatestVirtualCameraFrameRequest> = /*@__PURE__*/
  messageDesc(file_camera, 4);

/**
 * @generated from message camera.GetLatestVirtualCameraFrameResponse
 */
export type GetLatestVirtualCameraFrameResponse = Message<"camera.GetLatestVirtualCameraFrameResponse"> & {
  /**
   * @generated from field: bytes frame = 1;
   */
  frame: Uint8Array;
};

/**
 * Describes the message camera.GetLatestVirtualCameraFrameResponse.
 * Use `create(GetLatestVirtualCameraFrameResponseSchema)` to create a new message.
 */
export const GetLatestVirtualCameraFrameResponseSchema: GenMessage<GetLatestVirtualCameraFrameResponse> = /*@__PURE__*/
  messageDesc(file_camera, 5);

/**
 * @generated from message camera.SetVirtualCameraConfigRequest
 */
export type SetVirtualCameraConfigRequest = Message<"camera.SetVirtualCameraConfigRequest"> & {
  /**
   * @generated from field: string camera_name = 1;
   */
  cameraName: string;

  /**
   * @generated from field: float resolution_ratio = 2;
   */
  resolutionRatio: number;
};

/**
 * Describes the message camera.SetVirtualCameraConfigRequest.
 * Use `create(SetVirtualCameraConfigRequestSchema)` to create a new message.
 */
export const SetVirtualCameraConfigRequestSchema: GenMessage<SetVirtualCameraConfigRequest> = /*@__PURE__*/
  messageDesc(file_camera, 6);

/**
 * @generated from message camera.SetVirtualCameraConfigResponse
 */
export type SetVirtualCameraConfigResponse = Message<"camera.SetVirtualCameraConfigResponse"> & {
};

/**
 * Describes the message camera.SetVirtualCameraConfigResponse.
 * Use `create(SetVirtualCameraConfigResponseSchema)` to create a new message.
 */
export const SetVirtualCameraConfigResponseSchema: GenMessage<SetVirtualCameraConfigResponse> = /*@__PURE__*/
  messageDesc(file_camera, 7);

/**
 * @generated from message camera.PublishVirtualCameraRequest
 */
export type PublishVirtualCameraRequest = Message<"camera.PublishVirtualCameraRequest"> & {
  /**
   * @generated from field: string camera_name = 1;
   */
  cameraName: string;
};

/**
 * Describes the message camera.PublishVirtualCameraRequest.
 * Use `create(PublishVirtualCameraRequestSchema)` to create a new message.
 */
export const PublishVirtualCameraRequestSchema: GenMessage<PublishVirtualCameraRequest> = /*@__PURE__*/
  messageDesc(file_camera, 8);

/**
 * @generated from message camera.PublishVirtualCameraResponse
 */
export type PublishVirtualCameraResponse = Message<"camera.PublishVirtualCameraResponse"> & {
};

/**
 * Describes the message camera.PublishVirtualCameraResponse.
 * Use `create(PublishVirtualCameraResponseSchema)` to create a new message.
 */
export const PublishVirtualCameraResponseSchema: GenMessage<PublishVirtualCameraResponse> = /*@__PURE__*/
  messageDesc(file_camera, 9);

/**
 * @generated from message camera.UnpublishVirtualCameraRequest
 */
export type UnpublishVirtualCameraRequest = Message<"camera.UnpublishVirtualCameraRequest"> & {
  /**
   * @generated from field: string camera_name = 1;
   */
  cameraName: string;
};

/**
 * Describes the message camera.UnpublishVirtualCameraRequest.
 * Use `create(UnpublishVirtualCameraRequestSchema)` to create a new message.
 */
export const UnpublishVirtualCameraRequestSchema: GenMessage<UnpublishVirtualCameraRequest> = /*@__PURE__*/
  messageDesc(file_camera, 10);

/**
 * @generated from message camera.UnpublishVirtualCameraResponse
 */
export type UnpublishVirtualCameraResponse = Message<"camera.UnpublishVirtualCameraResponse"> & {
};

/**
 * Describes the message camera.UnpublishVirtualCameraResponse.
 * Use `create(UnpublishVirtualCameraResponseSchema)` to create a new message.
 */
export const UnpublishVirtualCameraResponseSchema: GenMessage<UnpublishVirtualCameraResponse> = /*@__PURE__*/
  messageDesc(file_camera, 11);

/**
 * @generated from service camera.CameraService
 */
export const CameraService: GenService<{
  /**
   * @generated from rpc camera.CameraService.GetCameraList
   */
  getCameraList: {
    methodKind: "unary";
    input: typeof GetCameraListRequestSchema;
    output: typeof GetCameraListResponseSchema;
  },
  /**
   * @generated from rpc camera.CameraService.GetLatestCameraFrame
   */
  getLatestCameraFrame: {
    methodKind: "unary";
    input: typeof GetLatestCameraFrameRequestSchema;
    output: typeof GetLatestCameraFrameResponseSchema;
  },
  /**
   * @generated from rpc camera.CameraService.GetLatestVirtualCameraFrame
   */
  getLatestVirtualCameraFrame: {
    methodKind: "unary";
    input: typeof GetLatestVirtualCameraFrameRequestSchema;
    output: typeof GetLatestVirtualCameraFrameResponseSchema;
  },
  /**
   * @generated from rpc camera.CameraService.SetVirtualCameraConfig
   */
  setVirtualCameraConfig: {
    methodKind: "unary";
    input: typeof SetVirtualCameraConfigRequestSchema;
    output: typeof SetVirtualCameraConfigResponseSchema;
  },
  /**
   * @generated from rpc camera.CameraService.PublishVirtualCamera
   */
  publishVirtualCamera: {
    methodKind: "unary";
    input: typeof PublishVirtualCameraRequestSchema;
    output: typeof PublishVirtualCameraResponseSchema;
  },
  /**
   * @generated from rpc camera.CameraService.UnpublishVirtualCamera
   */
  unpublishVirtualCamera: {
    methodKind: "unary";
    input: typeof UnpublishVirtualCameraRequestSchema;
    output: typeof UnpublishVirtualCameraResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_camera, 0);

