// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file camera.proto (package camera, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCameraListRequest, GetCameraListResponse, GetLatestCameraFrameRequest, GetLatestCameraFrameResponse, GetLatestVirtualCameraFrameRequest, GetLatestVirtualCameraFrameResponse, SetVirtualCameraConfigRequest, SetVirtualCameraConfigResponse } from "./camera_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service camera.CameraService
 */
export const CameraService = {
  typeName: "camera.CameraService",
  methods: {
    /**
     * @generated from rpc camera.CameraService.GetCameraList
     */
    getCameraList: {
      name: "GetCameraList",
      I: GetCameraListRequest,
      O: GetCameraListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc camera.CameraService.GetLatestCameraFrame
     */
    getLatestCameraFrame: {
      name: "GetLatestCameraFrame",
      I: GetLatestCameraFrameRequest,
      O: GetLatestCameraFrameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc camera.CameraService.GetLatestVirtualCameraFrame
     */
    getLatestVirtualCameraFrame: {
      name: "GetLatestVirtualCameraFrame",
      I: GetLatestVirtualCameraFrameRequest,
      O: GetLatestVirtualCameraFrameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc camera.CameraService.SetVirtualCameraConfig
     */
    setVirtualCameraConfig: {
      name: "SetVirtualCameraConfig",
      I: SetVirtualCameraConfigRequest,
      O: SetVirtualCameraConfigResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

