// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file camera.proto (package camera, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file camera.proto.
 */
export const file_camera: GenFile = /*@__PURE__*/
  fileDesc("CgxjYW1lcmEucHJvdG8SBmNhbWVyYSIWChRHZXRDYW1lcmFMaXN0UmVxdWVzdCIsChVHZXRDYW1lcmFMaXN0UmVzcG9uc2USEwoLY2FtZXJhX2xpc3QYASADKAkiMgobR2V0TGF0ZXN0Q2FtZXJhRnJhbWVSZXF1ZXN0EhMKC2NhbWVyYV9uYW1lGAEgASgJIi0KHEdldExhdGVzdENhbWVyYUZyYW1lUmVzcG9uc2USDQoFZnJhbWUYASABKAwywAEKDUNhbWVyYVNlcnZpY2USTAoNR2V0Q2FtZXJhTGlzdBIcLmNhbWVyYS5HZXRDYW1lcmFMaXN0UmVxdWVzdBodLmNhbWVyYS5HZXRDYW1lcmFMaXN0UmVzcG9uc2USYQoUR2V0TGF0ZXN0Q2FtZXJhRnJhbWUSIy5jYW1lcmEuR2V0TGF0ZXN0Q2FtZXJhRnJhbWVSZXF1ZXN0GiQuY2FtZXJhLkdldExhdGVzdENhbWVyYUZyYW1lUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message camera.GetCameraListRequest
 */
export type GetCameraListRequest = Message<"camera.GetCameraListRequest"> & {
};

/**
 * Describes the message camera.GetCameraListRequest.
 * Use `create(GetCameraListRequestSchema)` to create a new message.
 */
export const GetCameraListRequestSchema: GenMessage<GetCameraListRequest> = /*@__PURE__*/
  messageDesc(file_camera, 0);

/**
 * @generated from message camera.GetCameraListResponse
 */
export type GetCameraListResponse = Message<"camera.GetCameraListResponse"> & {
  /**
   * @generated from field: repeated string camera_list = 1;
   */
  cameraList: string[];
};

/**
 * Describes the message camera.GetCameraListResponse.
 * Use `create(GetCameraListResponseSchema)` to create a new message.
 */
export const GetCameraListResponseSchema: GenMessage<GetCameraListResponse> = /*@__PURE__*/
  messageDesc(file_camera, 1);

/**
 * @generated from message camera.GetLatestCameraFrameRequest
 */
export type GetLatestCameraFrameRequest = Message<"camera.GetLatestCameraFrameRequest"> & {
  /**
   * @generated from field: string camera_name = 1;
   */
  cameraName: string;
};

/**
 * Describes the message camera.GetLatestCameraFrameRequest.
 * Use `create(GetLatestCameraFrameRequestSchema)` to create a new message.
 */
export const GetLatestCameraFrameRequestSchema: GenMessage<GetLatestCameraFrameRequest> = /*@__PURE__*/
  messageDesc(file_camera, 2);

/**
 * @generated from message camera.GetLatestCameraFrameResponse
 */
export type GetLatestCameraFrameResponse = Message<"camera.GetLatestCameraFrameResponse"> & {
  /**
   * @generated from field: bytes frame = 1;
   */
  frame: Uint8Array;
};

/**
 * Describes the message camera.GetLatestCameraFrameResponse.
 * Use `create(GetLatestCameraFrameResponseSchema)` to create a new message.
 */
export const GetLatestCameraFrameResponseSchema: GenMessage<GetLatestCameraFrameResponse> = /*@__PURE__*/
  messageDesc(file_camera, 3);

/**
 * @generated from service camera.CameraService
 */
export const CameraService: GenService<{
  /**
   * @generated from rpc camera.CameraService.GetCameraList
   */
  getCameraList: {
    methodKind: "unary";
    input: typeof GetCameraListRequestSchema;
    output: typeof GetCameraListResponseSchema;
  },
  /**
   * @generated from rpc camera.CameraService.GetLatestCameraFrame
   */
  getLatestCameraFrame: {
    methodKind: "unary";
    input: typeof GetLatestCameraFrameRequestSchema;
    output: typeof GetLatestCameraFrameResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_camera, 0);

