{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera.CameraService exposing (getCameraList, getLatestCameraFrame, getLatestVirtualCameraFrame, publishVirtualCamera, unpublishVirtualCamera)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs getCameraList, getLatestCameraFrame, getLatestVirtualCameraFrame, publishVirtualCamera, unpublishVirtualCamera

-}

import Grpc.Internal
import Proto.Camera


{-| A template for a gRPC call to the method 'UnpublishVirtualCamera' sending a `UnpublishVirtualCameraRequest` to get back a `UnpublishVirtualCameraResponse`.

-}
unpublishVirtualCamera :
    Grpc.Internal.Rpc Proto.Camera.UnpublishVirtualCameraRequest Proto.Camera.UnpublishVirtualCameraResponse
unpublishVirtualCamera =
    Grpc.Internal.Rpc
        { service = "CameraService"
        , package = "camera"
        , rpcName = "UnpublishVirtualCamera"
        , encoder = Proto.Camera.encodeUnpublishVirtualCameraRequest
        , decoder = Proto.Camera.decodeUnpublishVirtualCameraResponse
        }


{-| A template for a gRPC call to the method 'PublishVirtualCamera' sending a `PublishVirtualCameraRequest` to get back a `PublishVirtualCameraResponse`.

-}
publishVirtualCamera :
    Grpc.Internal.Rpc Proto.Camera.PublishVirtualCameraRequest Proto.Camera.PublishVirtualCameraResponse
publishVirtualCamera =
    Grpc.Internal.Rpc
        { service = "CameraService"
        , package = "camera"
        , rpcName = "PublishVirtualCamera"
        , encoder = Proto.Camera.encodePublishVirtualCameraRequest
        , decoder = Proto.Camera.decodePublishVirtualCameraResponse
        }


{-| A template for a gRPC call to the method 'GetLatestVirtualCameraFrame' sending a `GetLatestVirtualCameraFrameRequest` to get back a `GetLatestVirtualCameraFrameResponse`.

-}
getLatestVirtualCameraFrame :
    Grpc.Internal.Rpc Proto.Camera.GetLatestVirtualCameraFrameRequest Proto.Camera.GetLatestVirtualCameraFrameResponse
getLatestVirtualCameraFrame =
    Grpc.Internal.Rpc
        { service = "CameraService"
        , package = "camera"
        , rpcName = "GetLatestVirtualCameraFrame"
        , encoder = Proto.Camera.encodeGetLatestVirtualCameraFrameRequest
        , decoder = Proto.Camera.decodeGetLatestVirtualCameraFrameResponse
        }


{-| A template for a gRPC call to the method 'GetLatestCameraFrame' sending a `GetLatestCameraFrameRequest` to get back a `GetLatestCameraFrameResponse`.

-}
getLatestCameraFrame :
    Grpc.Internal.Rpc Proto.Camera.GetLatestCameraFrameRequest Proto.Camera.GetLatestCameraFrameResponse
getLatestCameraFrame =
    Grpc.Internal.Rpc
        { service = "CameraService"
        , package = "camera"
        , rpcName = "GetLatestCameraFrame"
        , encoder = Proto.Camera.encodeGetLatestCameraFrameRequest
        , decoder = Proto.Camera.decodeGetLatestCameraFrameResponse
        }


{-| A template for a gRPC call to the method 'GetCameraList' sending a `GetCameraListRequest` to get back a `GetCameraListResponse`.

-}
getCameraList : Grpc.Internal.Rpc Proto.Camera.GetCameraListRequest Proto.Camera.GetCameraListResponse
getCameraList =
    Grpc.Internal.Rpc
        { service = "CameraService"
        , package = "camera"
        , rpcName = "GetCameraList"
        , encoder = Proto.Camera.encodeGetCameraListRequest
        , decoder = Proto.Camera.decodeGetCameraListResponse
        }
