{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Camera.CameraService exposing (getCameraList)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 6.33.1
- the following specification files: `proto/camera.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs getCameraList

-}

import Grpc.Internal
import Proto.Camera


{-| A template for a gRPC call to the method 'GetCameraList' sending a `GetCameraListRequest` to get back a `GetCameraListResponse`.

-}
getCameraList : Grpc.Internal.Rpc Proto.Camera.GetCameraListRequest Proto.Camera.GetCameraListResponse
getCameraList =
    Grpc.Internal.Rpc
        { service = "CameraService"
        , package = "camera"
        , rpcName = "GetCameraList"
        , encoder = Proto.Camera.encodeGetCameraListRequest
        , decoder = Proto.Camera.decodeGetCameraListResponse
        }
